service: google-analytics
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  secrets: ${file(./config/secrets.${opt:stage, 'dev'}.yml)}
  serverless-offline:
    httpPort: 8080

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x

functions:
  api:
    environment:
      SIGNING_SECRET: ${self:custom.secrets.signingSecret}
      STAGE: ${opt:stage, 'dev'}
      RELEASE_VERSION: ${env:CIRCLE_SHA1, env:RELEASE_VERSION}
    handler: build/src/index.handler
    events:
      - http:
          path: /{any+}
          method: ANY
