service: google-analytics
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  environment: ${file(./config/serverless-env.${opt:stage, self:provider.stage}.yml)}
  serverless-offline:
    httpPort: 8080

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x

functions:
  api:
    environment:
      SIGNING_SECRET: ${self:custom.environment.SIGNING_SECRET}
      STAGE: ${opt:stage, self:provider.stage}
    handler: build/src/index.handler
    events:
      - http:
          path: /{any+}
          method: ANY
